"""initial migration

Revision ID: 9de47c5cf2bf
Revises: 
Create Date: 2023-06-04 13:03:49.502494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de47c5cf2bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('your_table_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('your_table_name',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('requirement', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('agreed_terms', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='your_table_name_pkey')
    )
    # ### end Alembic commands ###
